# Generated by Django 5.1 on 2024-08-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='decription',
            new_name='description',
        ),
    ]
